spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

  # 데이터베이스 설정
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA 설정
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

  # JWT 설정
  jwt:
    secret: ${JWT_SECRET_KEY}
    token:
      access-expiration-time: ${JWT_ACCESS_EXPIRATION}
      refresh-expiration-time: ${JWT_REFRESH_EXPIRATION}

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  # 로깅 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.nfjs.delivery: debug

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always
